name: sistema
services:
  mysql:
    container_name: banco-sql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'consultorio'
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - /c/Users/Pichau/Desktop/db:/var/lib/mysql
  
  flask:
    container_name: flask-web
    build: ./app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      SECRET_KEY: ${SECRET_KEY}
      DB_USER: ${DB_USER} 
      DB_PASSWORD: ${DB_PASSWORD} 
    restart: always
    entrypoint: ["sh", "-c", "sleep 10 && flask run --host=0.0.0.0"]
    depends_on:
      - mysql


