name: flaskEsql
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'crud'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - PATH THO VOLUME  PATH TO COLUME  PATH TO VOLUME  PATH TO VOLUME
  
  crud:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      SECRET_KEY: ${SECRET_KEY}
    restart: always
    entrypoint: ["sh", "-c", "sleep 10 && flask run --host=0.0.0.0"]
    depends_on:
      - db


